In [1]:
import numpy as np

In [2]:
a=np.arange(0,100).reshape(20,5) #array created

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

index markdown error learned here


In [4]:
rows=np.random.randint(0,10,size=5)
columns=np.random.randint(0,5,size=5)

In [5]:
a[rows,columns] = -1 # add -1 randomly to add missing values

In [6]:
a

array([[ 0,  1,  2, -1,  4],
       [ 5,  6,  7, -1,  9],
       [-1, 11, 12, 13, -1],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, -1, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [7]:
for i in range(a.shape[1]): #check every column
    curr_pos=a[:, i] #current position element temp variable
    clear_mean=curr_pos[curr_pos!=-1].mean()
    curr_pos[curr_pos ==-1]=clear_mean #mean added to missing value area

feature scaling use min-max normalization

In [8]:
a_min=a.min(axis=0)

In [9]:
a_max=a.max(axis=0)


In [10]:
a_scaled=(a-a_min)/(a_max-a_min) #min-max norm

In [11]:
a_scaled

array([[0.        , 0.        , 0.        , 0.49411765, 0.        ],
       [0.05263158, 0.05263158, 0.05263158, 0.49411765, 0.05263158],
       [0.51578947, 0.10526316, 0.10526316, 0.        , 0.51578947],
       [0.15789474, 0.15789474, 0.15789474, 0.05882353, 0.15789474],
       [0.21052632, 0.21052632, 0.21052632, 0.11764706, 0.21052632],
       [0.26315789, 0.50526316, 0.26315789, 0.17647059, 0.26315789],
       [0.31578947, 0.31578947, 0.31578947, 0.23529412, 0.31578947],
       [0.36842105, 0.36842105, 0.36842105, 0.29411765, 0.36842105],
       [0.42105263, 0.42105263, 0.42105263, 0.35294118, 0.42105263],
       [0.47368421, 0.47368421, 0.47368421, 0.41176471, 0.47368421],
       [0.52631579, 0.52631579, 0.52631579, 0.47058824, 0.52631579],
       [0.57894737, 0.57894737, 0.57894737, 0.52941176, 0.57894737],
       [0.63157895, 0.63157895, 0.63157895, 0.58823529, 0.63157895],
       [0.68421053, 0.68421053, 0.68421053, 0.64705882, 0.68421053],
       [0.73684211, 0.73684211, 0.

In [12]:
weights = np.array([0.1, 0.1, 0.2, 0.3, 0.3])

In [13]:
a.shape

(20, 5)

In [14]:
weights.shape

(5,)

In [15]:
weighted_matrix=a_scaled * weights

In [16]:
patient_scores = weighted_matrix.sum(axis=1)

In [17]:
highest_risk_index = patient_scores.argmax()

In [18]:
print(f"Patient at index {highest_risk_index} has the highest risk score of {patient_scores[highest_risk_index]:.2f}")

Patient at index 19 has the highest risk score of 1.00
