In [1]:
import numpy as np

In [7]:
image=np.arange(0,25,dtype='uint8').reshape(5,5)*10

In [8]:
brightened=image+50
flattened=image.ravel()

In [9]:
column_total=image.sum(axis=0)

In [10]:
print("Original Image Matrix:\n", image)

Original Image Matrix:
 [[  0  10  20  30  40]
 [ 50  60  70  80  90]
 [100 110 120 130 140]
 [150 160 170 180 190]
 [200 210 220 230 240]]


In [13]:
print("\nVertical Brightness (Axis 0 Sum):\n", column_total)


Vertical Brightness (Axis 0 Sum):
 [500 550 600 650 700]
